### ISSUE TITLE
Fastlane Publish to AppStore

### ISSUE THREAD

**Issue by nhaynes** [AdGem/iOS-Sample-App#5]
We want to add Fastlane to this project and use it to publish newly released versions to the app store.

We will need to add a new `release` workflow that executes when a new version is released to github (via Semantic release)

**Comment by nhaynes** [comment]
We don't want to publish to App Store. Just Testflight.

**Comment by dakotawashok** [comment]
There might be a blocker with this, in that the credentials become exposed why making releases. This needs some more context from @cfabianleon or @eury-fsl
